name: YouTube Scraper

on:
  # 定期実行（6時間ごと）
  schedule:
    - cron: '0 */6 * * *'
  
  # 手動実行
  workflow_dispatch:
    inputs:
      search_query:
        description: '検索クエリ'
        required: false
        default: 'ChatGPT'
        type: string
      max_results:
        description: '最大取得件数'
        required: false
        default: '50'
        type: string
      use_browserless:
        description: 'Browserlessを使用'
        required: false
        default: true
        type: boolean

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Playwright browsers
      run: playwright install chromium
    
    - name: Create necessary directories
      run: |
        mkdir -p logs
        mkdir -p data
    
    - name: Run scraper
      env:
        BROWSERLESS_URL: ${{ secrets.BROWSERLESS_URL }}
        GOOGLE_SHEETS_CREDS: ${{ secrets.GOOGLE_SHEETS_CREDS }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
        DEFAULT_SEARCH_QUERY: ${{ github.event.inputs.search_query || 'ChatGPT' }}
        MAX_RESULTS: ${{ github.event.inputs.max_results || '50' }}
      run: |
        if [ "${{ github.event.inputs.use_browserless }}" == "true" ]; then
          python main.py --query "$DEFAULT_SEARCH_QUERY" --max-results $MAX_RESULTS --use-browserless
        else
          python main.py --query "$DEFAULT_SEARCH_QUERY" --max-results $MAX_RESULTS
        fi
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: scraper-logs
        path: |
          logs/
          DEVELOPMENT.md
        retention-days: 30
    
    - name: Upload data
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: scraper-data
        path: data/
        retention-days: 90
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "スクレイピングジョブが失敗しました。"
        echo "エラーログを確認してください。"